### ISSUE TITLE
Demo code does not work on the latest version of sveltekit 1.5.0

### ISSUE THREAD

**Issue by The-Real-Thisas** [timgblack/pdf.svelte#3]
Demo code does not work on the latest version of sveltekit 1.5.0.

Internal server error: global$1.XMLHttpRequest is not a constructor
      at checkTypeSupport (file:///Users/edin/Desktop/paper-sc/paper-sc/node_modules/@bundled-es-modules/pdfjs-dist/build/pdf.js:11402:11)
      at file:///Users/edin/Desktop/paper-sc/paper-sc/node_modules/@bundled-es-modules/pdfjs-dist/build/pdf.js:11421:38
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25) (x3)
TypeError: global$1.XMLHttpRequest is not a constructor
    at checkTypeSupport (file:///Users/edin/Desktop/paper-sc/paper-sc/node_modules/@bundled-es-modules/pdfjs-dist/build/pdf.js:11402:11)
    at file:///Users/edin/Desktop/paper-sc/paper-sc/node_modules/@bundled-es-modules/pdfjs-dist/build/pdf.js:11421:38
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

I thought it might be because its trying to run the code serverside so I did attempt to use onmount. 

```svelte
<script>
  import PDFViewer from "pdf.svelte";
  import { onMount } from "svelte";

  // Required - either a link to the PDF, the contents wrapped in {data: YOUR DATA HERE}, or an int array
  // This is passed straight to pdfjs.getDocument
  const pdf =
    "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf";

  // These classes are set on the various elements
  const classes = {
    overall: null,
    controls: null,
    container: null,
  };

  const options = {
    // "paged" or "all"
    display: "paged",
    // "dark" or "light" or your own
    theme: "dark",
    // allow double click/tap to zoom between 1 and 1.5x
    autoZoomEnabled: false,
    // baseline superscale resolution to render at
    upscale: 4,
  };

  let zoom = 1,
    zoomIn,
    zoomOut;

  // The current page number
  let currentPage;

  // To override the text between the forward and back buttons
  const pageNumberText = (currentPage, maximmPages) =>
    currentPage + "/" + maximumPages;

    let mounted = false;

    onMount(() => {
        mounted = true;
        });

</script>


{#if mounted}
  <PDFViewer
    {pdf}
    {classes}
    {options}
    {zoom}
    bind:zoomIn
    bind:zoomOut
    {pageNumberText}
    bind:currentPage
  />
{/if}
```

Did't fix it.

**Comment by timgblack** [comment]
This should be fixed in v0.4.0 which is up on npm now. Can you confirm it's working correctly now @The-Real-Thisas?
